all : output 

output: main.cpp Account.h Account.cpp ElectricSpot.h ElectricSpot.cpp admin.h admin.cpp Exit.h Exit.cpp HandicappedSpot.h HandicappedSpot.cpp LargeSpot.h LargeSpot.cpp MotorbikeSpot.h MotorbikeSpot.cpp Parking_attendant.h Parking_attendant.cpp ParkingDisplayBoard.h ParkingDisplayBoard.cpp ParkingFloor.h ParkingFloor.cpp ParkingRate.h ParkingRate.cpp Person.h Person.cpp
	g++ -o output main.cpp Account.cpp ElectricSpot.cpp admin.cpp Exit.cpp HandicappedSpot.cpp LargeSpot.cpp MotorbikeSpot.cpp Parking_attendant.cpp ParkingDisplayBoard.cpp ParkingFloor.cpp ParkingRate.cpp Person.cpp

clean:
	rm -f output